<?php
require_once("uc_bihang.pages.inc");
require_once("/lib/Bihang.php");

define ('BIHANG_WEBSITE', "http://www.bihang.com");
define ('BIHANG_BITCOIN_LOGO_PATH', base_path() . drupal_get_path('module', 'uc_bihang') . '/bitcoin-accepted.png');
define ('BIHANG_NOTIFY_URL', "uc_bihang/notifications");
define ('BIHANG_INVOICE_EXPIRATION_TIME', "10"); // in minutes; keep as a string

/**
 * Settings form for the bihang payment method module.
 * Not directly hooked into by Ubercart; called by
 * uc_payment_method_bihang()
 *
 * @return array
 */
function uc_bihang_settings_form()
{
    global $base_url;

    $form          = array();
    $form['general'] = array(
        '#type'        => 'fieldset',
        '#title'       => t('General settings'),
        '#collapsible' => FALSE,
        '#collapsed'   => FALSE,
    );
    $form['general']['uc_bihang_api_key'] = array(
        '#type'          => 'textfield',
        '#title'         => t('API Key'),
        '#default_value' => variable_get('uc_bihang_api_key', ''),
       );
    $form['general']['uc_bihang_api_secret'] = array(
        '#type'    => 'textfield',
        '#title'   => t('API Secret'),
        '#default_value' => variable_get('uc_bihang_api_secret', ''),
    );

    return $form;
}

/**
 * Implements hook_menu().
 *
 * @return array
 */
function uc_bihang_menu()
{
    // Always accessible, accepts POST data from bihang's servers
    // when being notified of status changes to an invoice.
    $items[BIHANG_NOTIFY_URL] = array(
        'title'           => 'bihang Notifications',
        'access callback' => TRUE,
        'page callback'   => 'uc_bihang_notification',
        'type'            => MENU_CALLBACK,
        'file'            => 'uc_bihang.pages.inc',
    );

    return $items;
}

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function uc_bihang_help($path, $arg)
{
    $o = '';  // declare your output variable
    switch ($path)
    {
    case "admin/help#bihang":
        $o .= '<p>' . t('Implements the acceptance of bitcoin payments through the') . " bihang.com " . t('API.') . '</p>';
        break;
    }
    return $o;
} // end function - uc_bihang_help


/**
 * Implements hook_uc_payment_method().
 *
 * @return array
 */
function uc_bihang_uc_payment_method()
{

        $title = '<img src="' . BIHANG_BITCOIN_LOGO_PATH .
            '" style="position:relative; top:5px; margin-right:6px;" />' .
            t('Pay with Bitcoins via Bihang.');

        $methods[] = array(
            'id'         => 'bihang',
            'name'       => t('Bihang'),
            'title'      => $title,
            'review'     => t('Bitcoin via bihang'),
            'desc'       => t('Make a payment using bitcoins.'),
            'callback'   => 'uc_payment_method_bihang',
            'weight'     => 1,
            'checkout'   => TRUE,
            'no_gateway' => TRUE,
        );

        return $methods;
}


/**
 * Implementation of hook_uc_order().
 *
 * @param $op
 * @param $arg1
 * @param $arg2
 */


function uc_bihang_uc_order($op, $order, $arg2)
{
    global $base_url;


    if (($order->payment_method == 'bihang') && (!variable_get('uc_bihang_debug_mode', 0) || 
        user_access('access administration menu')))
    {
        switch ($op)
        {

        case 'new':
        case 'save':
            break;
        case 'total':
            break;
        case 'load':      
            break;
        case 'submit':
            $client = Bihang::withApiKey(variable_get('uc_bihang_api_key',''),variable_get('uc_bihang_api_secret',''));

            if( variable_get('clean_url', '0') == 0 ){
                $callback_url = $base_url . '/?q=uc_bihang/notifications'; 
                $success_url  = $base_url . '/?q=cart/checkout'; 
            }else{
                $callback_url = $base_url . '/uc_bihang/notifications';
                $success_url  = $base_url . '/cart/checkout'; 
            }

            $site_url = variable_get('uc_bihang_base_url', $base_url);
            $params = array(
                        'name'           => 'Order #'.$order->order_id,
                        'price'          => uc_order_get_total($order),
                        'price_currency' => $order->currency,
                        'callback_url'   => $callback_url,
                        'success_url'    => $success_url,
                );
            $result = $client->buttonsButton($params);
            var_dump($result);
            if( $result && $result->button ){
                db_insert('uc_payment_bihang')
                    ->fields(array(
                        'button_id'    => $result->button->id,
                        'order_id'     => $order->order_id,
                    ))
                    ->execute();
            }
            break;
        } // end switch - check for order action taken
    } // end if - check to make sure payment method is 'bihang', etc.
} // end function - uc_bihang_uc_order

/**
 * Payment method callback for the bihang payment method
 *
 * @param $op
 * @param $order
 */
function uc_payment_method_bihang($op, &$order)
{
    switch ($op)
    {
    case 'settings':
        return uc_bihang_settings_form();
        break;

    case 'cart-details':
        $txt = '<br /><br />' . t('The price will be converted to bitcoins at the current to-the-minute exchange rate, and you will have') . ' ' . BIHANG_INVOICE_EXPIRATION_TIME . ' ' . t('minutes to send payment before the invoice expires.');
        return array('#markup' => $txt);
        break;
    case 'customer-view':
        if( $order->order_status == 'pending' ){
            $button_id = db_query("SELECT button_id FROM {uc_payment_bihang} WHERE order_id = :order_id", array(':order_id' => $order->order_id))->fetchField();
                // display the invoice ID, with a link to the url
            $url = BIHANG_WEBSITE.'/merchant/mPayOrderStemp1.do?buttonid='.$button_id;
            $txt =  '<a href="' . $url . '" target="_blank" class="form-submit">Pay It</a>';
            return array('#markup' => $txt);           
        } 

        break;
    }
} // end function - uc_payment_method_bihang

